### ISSUE TITLE
Protokoll Tutortreffen 04.05.

### ISSUE THREAD

**Issue by bakoe** [HPI-SWA-Teaching/OpenSqueakMap#10]
# Termine
- Vortrag: 06.07.2017
- Konsultation: 26.06.2017

# Organisatorisches
- Betreuerin ist gleichzeitig Betreuer und Kunde (nimmt User Stories ab)
- anfangs einwöchige Treffen, später auch zweiwöchig möglich
- Trello-Board von der Vorgänger-Gruppe wird uns von Betreuerin geschickt
- Der Lehrstuhl fügt uns zum (evtl. geforkten) GitHub-Repo hinzu
	- falls das bis 05.05. nicht passiert ist: noch mal melden!

# Begrifflichkeiten (User Stories, Praktiken)
- User Stories 
	- legen wir selbst an und schätzen sie auch selbst (mit Punkten/Planning Poker/Keksen/…)
	- Kunde vergibt ebenfalls Punkte (z. B. 30) auf die User Stories nach Prioritäten
	- sollten permanent sein (z. B. GitHub Issues oder Trello-Karten)
	- gern auch auf Karten ausdrucken/aufschreiben und mitbringen
	- Akzeptanzkriterien und Anforderungen klar beschreiben
	- z. B. „As a Teacher I want to …“
	- wichtig: Dass man es versteht und es sinnvoll ist
- Praxis „Simple Design“ + eine weitere selbst auswählen! (es können beliebig viele ausgewählt werden)
	- z. B. Planning Poker

# Inhalt der Präsentation
- Wie wurden Praktiken angewandt?
- Was haben wir geschaffen?
- Wie haben sich die Praktiken auf unseren Prozess ausgewirkt?
- optimal: Feststellen, dass die Praktiken sinnvoll waren 

# Thema Ladezeiten
- momentan sind Ladezeiten sehr hoch, weil immer alle Kartendaten geladen werden
- besser wäre es, wenn man z. B. nur Flüsse oder nur Wege laden können

# Erste Woche (bis zum nächsten Treffen)
- mit Legacy Code auseinandersetzen (versuchen, Code zum Laufen zu bringen)
- evtl. bestehende User Stories/Issues anschauen
- eine weitere Praxis auswählen (neben Simple Design) – kann Unterpraxis von XP, aber auch sowas wie TTD sein
- erste User Stories (Welche Features hätten wir gern?) erstellen
	- im Optimalfall genug User Stories, um einen Sprint (eine Woche) damit mit Arbeit füllen zu können
- neue User Stories schätzen (z. B. mittels Planning Poker/Bucket Estimation/Affinity Estimation)

**Comment by birneamstiel** [comment]
Ins Wiki übernehmen...
