### ISSUE TITLE
[1h] Nacharbeit: Markieren und Speichern von Orten ermöglichen

### ISSUE THREAD

**Issue by bakoe** [HPI-SWA-Teaching/OpenSqueakMap#13]
### Was?
Als **Nutzer**, der die Karte mehrmals verwendet, möchte ich wichtige Orte markieren und beschriften können.

### Akzeptanzkriterien
- Nutzer sind in der Lage, eine Position auf der Karte mit einem grafischen Marker zu versehen und diesen Marker zu beschriften. 
- Gesetzte Marker werden gespeichert und somit über mehrere Sitzungen hinweg persistent angezeigt.
- Nutzer sind in die Lage, gesetzte Marker wieder zu entfernen.

**Comment by lheilmann** [comment]
Erster Ansatz:
- Marker können auf RenderObjects gesetzt und von diesen entfernt werden
- Die gesetzten Marker werden in einer JSON-Datei gespeichert
- Das Setzen und Entfernen eines Markers wird vorerst durch das Morphic-Event #keystroke ausgelöst, welches bei jedem Key abgefeuert wird (Achtung: Verbesserungsbedarf!) - demnach wird ein Marker wieder gelöscht, wenn man das Event auf dem geg. RenderObject erneut abfeuert
[json.zip](https://github.com/HPI-SWA-Teaching/OpenSqueakMap/files/1026134/json.zip)
