### ISSUE TITLE
[8h] Hinzufügen von noch nicht gezeichneten Objekten

### ISSUE THREAD

**Issue by lheilmann** [HPI-SWA-Teaching/OpenSqueakMap#30]
### Was?
Als **Nutzer** möchte, dass auch Objekte die bisher noch nicht gezeichnet werden sichtbar werden (z.B. Wasser).

### Einschränkungen

**Comment by bakoe** [comment]
Neben Wasser ggf. auch andere Elemente hinzufügen!
