### ISSUE TITLE
[8h] Nacharbeit: Caching ermöglichen

### ISSUE THREAD

**Issue by lheilmann** [HPI-SWA-Teaching/OpenSqueakMap#31]
### Was?
Als **Nutzer** möchte ich, dass ein- und derselbe Ort beim erneuten Öffnen nicht jedes Mal neu geladen werden muss.

### Akzeptanzkriterien
* Caching soll definitiv innerhalb einer Squeak-Session ermöglicht werden
* Caching muss nicht zwangsläufig so implementiert werden, dass nach dem Schließen des Images Chunks zwischengespeichert bleiben

### Einschränkungen

**Comment by bakoe** [comment]
Aktueller Stand vom 15.06.:
- Cache hat keine Maximalgröße
- Cache ist Singleton, was die Multi-Instanz-Fähigkeit von OpenSqueakMap verhindert
