### ISSUE TITLE
[4h] „Layer“ für Text und Anmerkungen über Kartenelementen anlegen

### ISSUE THREAD

**Issue by bakoe** [HPI-SWA-Teaching/OpenSqueakMap#50]
Um Elemente wie Straßennamen oder Anmerkungen immer über der Karte anzeigen zu können, möchte ich als **Entwickler** herausfinden, ob und wie ein solcher „Layer“ oberhalb der Kartenelemente angelegt werden kann.

**Comment by birneamstiel** [comment]
Erkenntnisse nach Gespräch mit Tobias:

- _Morphic_ bietet keine Möglichkeit an von Haus aus verschiedene Layer zu rendern
- als Lösung bleiben uns zwei verschiedene Möglichkeiten:
  1. Die Submorph-Beziehungen zwischen den Straßen und den Straßennamen beibehalten, sodass da weiterhin eine enge, semantische Kopplung besteht. Dann müssten wir den Rendervorgang insofern anpassen, dass wir in unseren _Morphs_ die `drawOn` überschreiben und von unserem _Viewport_ aus verschiedene "Render-Druchgänge" initiieren: Erst alles außer Straßennamen, im nächsten Durchlauf dann die Straßennamen noch einmal darauf rendern.
  2. Die Straßennamen in einer separaten Morph-Hierarchie verwalten. Damit könnte man diese im Viewport "ganz nach oben" schieben, sodass sie immer ganz oben gerendert werden. Parallel dazu müsste man durch eine Art Komposition die Verbindung zwischen dem jeweiligen _RenderingObject_ (Straße) und _TextMorph_ (StraßenName) implementieren.
