### ISSUE TITLE
Gesammeltes Refactoring

### ISSUE THREAD

**Issue by birneamstiel** [HPI-SWA-Teaching/OpenSqueakMap#58]
Nur template, worauf man in PR's verlinken kann...

**Comment by bakoe** [comment]
![image](https://user-images.githubusercontent.com/807665/27684865-11ed3bf4-5ccc-11e7-8d9f-024d34f64bfa.png)

Typo im Methodenname (i in Initialize fehlt)

**Comment by bakoe** [comment]
![image](https://user-images.githubusercontent.com/807665/27684884-26b56ade-5ccc-11e7-8e8b-f93ac22377f5.png)

auskommentierter Code

**Comment by lheilmann** [comment]
* Methoden-Klassifizierung
* Klassen-Kommentare
* Methoden-Kommentare
