### ISSUE TITLE
To Do bis Do 11.05.

### ISSUE THREAD

**Issue by bakoe** [HPI-SWA-Teaching/OpenSqueakMap#9]
- [ ] SWT-Folien zu „agilen Praktiken“ (z.B. XP) anschauen, um neben *Simple Design* noch eine weitere Praxis für unseren Prozess auswählen zu können – https://hpi.de/internalfiles/materialien/FG_SoftwareArchitekturen/SoftwareEngineering_V/Handouts/Swt1_U04_XP.pdf (ab Folie 51)
- [ ] Neue User Stories überlegen
- [ ] Legacy-Code im Image auschecken; versuchen, insb. die Rendering-Konfiguration nutzen zu können (unsere Vorgänger haben z.B. das Rendering von Gebäuden eingebaut und wir sind noch nicht dahinter gestiegen, wie man das aktiviert)

**Comment by birneamstiel** [comment]
Ich wäre dafür das _Planning Game_ als Praxis auszuwählen die wir über _Simple Design_ hinaus verwenden und vorstellen... Sieht ganz sinnvoll und nicht so kompliziert aus ;-)

http://wiki.c2.com/?PlanningGame


![planninggameflowchart](https://cloud.githubusercontent.com/assets/5410949/25900621/5920cb58-3594-11e7-8b73-54dffccaf927.gif)

**Comment by birneamstiel** [comment]
So solls angeblich aussehen:

<img width="1341" alt="screen shot 2017-05-10 at 15 25 18" src="https://cloud.githubusercontent.com/assets/5410949/25900786/e8a16cc4-3594-11e7-9b44-c91bc6fb4fc6.png">

**Comment by danthe96** [comment]
Ich habe letztes Jahr an dem Projekt gearbeitet, wenn ihr noch nicht genau über die Struktur Bescheid wisst, könnt ihr euch hier [unsere Endpräsentation](https://docs.google.com/presentation/d/1c9nDcYyeMQdn5nhArEPRRX6KzgJmc3HvqGgjeOJROWI/edit?usp=sharing) und den [Screencast](https://www.youtube.com/watch?v=KzrTAvoBN9c) von damals ansehen.

**Comment by HendrikSchmidt** [comment]
Vielen Dank!
